# Originally generated by: make -C buildroot O=../ outputmakefile
#  - Re-run to bring into sync with Buildroot.
#  - Overrides/workarounds will need to be re-applied.

# 68040 m68k: Workaround SCSI crash when the kernel is built with -O2
MAKEOVERRIDES := LINUX_CFLAGS="-freorder-blocks-algorithm=simple"

# Original Makefile follows
ifeq ("$(origin V)", "command line")
VERBOSE := $(V)
endif
ifneq ($(VERBOSE),1)
Q := @
endif

lastword = $(word $(words $(1)),$(1))
makedir := $(dir $(call lastword,$(MAKEFILE_LIST)))

MAKEARGS := -C buildroot
MAKEARGS += O=$(if $(patsubst /%,,$(makedir)),$(CURDIR)/)$(patsubst %/,%,$(makedir))

MAKEFLAGS += --no-print-directory

.PHONY: _all $(MAKECMDGOALS)

all	:= $(filter-out Makefile,$(MAKECMDGOALS))

_all:
	$(Q)umask 0022 && $(MAKE) $(MAKEARGS) $(all)

Makefile:;

$(all): _all
	@:

%/: _all
	@:

